[package]
name = "monkey-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.monkey]
path = ".."

[[bin]]
name = "parser"
path = "fuzz_targets/fuzz_parser.rs"
test = false
doc = false
bench = false
